/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/theme/brand.theme.ts
 * Command: astryx theme build lib/theme/brand.theme.ts --out lib/theme/brand-theme.css
 * Generated: 2026-07-23T07:41:18.519Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
