/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/theme/brand.theme.ts
 * Command: astryx theme build lib/theme/brand.theme.ts --out lib/theme/brand-theme.css
 * Generated: 2026-07-23T05:48:30.096Z
 */

/// <reference path="./brand.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const brandTheme: DefinedTheme;
